apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}-{{.Values.env}}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
                exec:
                    command: ['npm', 'run', 'deploy']
          env:
            - name: DOCKERHUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dockerhub-bot-creds
                  key: credential
            - name: COSMOS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: cosmos-connect-string
                  key: credential
            - name: FBB_BOT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fbb-bot-client-id
                  key: credential
            - name: FBB_BOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fbb-bot-secret
                  key: credential
            - name: FBB_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fbb-bot-token
                  key: credential
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m" # 500milliCPUs (1/2 CPU)
            limits:
              memory: "128Mi"
              cpu: "100m"
